[workspace]
members = [
    "hdm_api",
    "config",
    "configmanager"
]
resolver = "2"


[workspace.dependencies]
wlrootbackends = { path = "wlrootbackends", optional = true }

[features]
rust_build = []
c_ffi = ["wlrootbackends"]
